name: flutter_translated_text
description: "A widget for translating text using GoogleTranslator"
version: 1.0.0
homepage: https://github.com/gabrielpacheco23/translated_text

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
